apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ekmai-collab

resources:
  - postgres.yaml
  - mattermost.yaml
  - gitlab-proxy.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: ekmai
  app.kubernetes.io/managed-by: kustomize
