---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mattermost-db-policy
  namespace: ekmai-collab
spec:
  podSelector:
    matchLabels:
      app: mattermost-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: mattermost-app
      ports:
        - protocol: TCP
          port: 5432
---
# 允許 Gateway 存取 Mattermost
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mattermost-ingress-policy
  namespace: ekmai-collab
spec:
  podSelector:
    matchLabels:
      app: mattermost-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/component: gateway
      ports:
        - protocol: TCP
          port: 8065
