---
apiVersion: v1
kind: Namespace
metadata:
  name: ekmai-gateway
  labels:
    app.kubernetes.io/part-of: ekmai
    app.kubernetes.io/component: gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: ekmai-iam
  labels:
    app.kubernetes.io/part-of: ekmai
    app.kubernetes.io/component: iam
---
apiVersion: v1
kind: Namespace
metadata:
  name: ekmai-collab
  labels:
    app.kubernetes.io/part-of: ekmai
    app.kubernetes.io/component: collaboration
---
apiVersion: v1
kind: Namespace
metadata:
  name: ekmai-kb
  labels:
    app.kubernetes.io/part-of: ekmai
    app.kubernetes.io/component: knowledge-base
---
apiVersion: v1
kind: Namespace
metadata:
  name: ekmai-observe
  labels:
    app.kubernetes.io/part-of: ekmai
    app.kubernetes.io/component: observability
