apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ekmai-kb

resources:
  - wikijs.yaml
  - outline.yaml
  - outline-config.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: ekmai
  app.kubernetes.io/managed-by: kustomize
