apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ekmai-es
  namespace: ekmai-observe
spec:
  version: 8.14.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        xpack.security.enabled: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              resources:
                requests:
                  memory: 1Gi
                  cpu: "500m"
                limits:
                  memory: 2Gi
                  cpu: "1000m"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
