apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ekmai-observe

resources:
  - elasticsearch.yaml
  - logstash.yaml
  - metricbeat.yaml

commonLabels:
  app.kubernetes.io/part-of: ekmai
  app.kubernetes.io/managed-by: kustomize

# 注意：ECK Operator 需要預先安裝
# kubectl create -f https://download.elastic.co/downloads/eck/2.14.0/crds.yaml
# kubectl apply -f https://download.elastic.co/downloads/eck/2.14.0/operator.yaml
